// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlaywrightSandbox.Web.Data;

#nullable disable

namespace PlaywrightSandbox.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515070943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("PlaywrightSandbox.Web.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The iconic 1v1 fighter that defined the genre.",
                            Genre = "Fighting",
                            Rating = 9.5,
                            ReleaseYear = 1991,
                            Title = "Street Fighter II"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Brutally realistic fighter famous for its fatalities.",
                            Genre = "Fighting",
                            Rating = 9.0,
                            ReleaseYear = 1992,
                            Title = "Mortal Kombat"
                        },
                        new
                        {
                            Id = 3,
                            Description = "SNK's power-gauge fighter that introduced super moves.",
                            Genre = "Fighting",
                            Rating = 8.5,
                            ReleaseYear = 1992,
                            Title = "Art of Fighting"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
